//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int CodMovimiento { get; set; }
        public Nullable<System.DateTime> FechaMov { get; set; }
        public string TipoMov { get; set; }
        public Nullable<int> CuentaDestino { get; set; }
        public Nullable<int> CuentaOrigen { get; set; }
        public Nullable<int> Monto { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
        public virtual Cuenta Cuenta1 { get; set; }
        public virtual TipoMovimiento TipoMovimiento { get; set; }
    }
}
